version: "1.0"
services:
  mysql:
    restart: always
    image: mysql:8.0.25
    volumes:
      - "./data/sql:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: c%>PQ799@!
    ports:
      - "3306:3306"

  redis:
    restart: always
    image: redis
    ports:
      - "13579:6379"

  tomcat:
    restart: always
    image: tomcat:9
    ports:
      - "8088:8080"
    volumes:
      - "./target/:/usr/local/tomcat/webapps/"
      - "./data/machine/:/var/lib/xwash/"
