version: "1.0"
services:
  mysql:
    restart: always
    image: mysql:8.0.22
    volumes:
      - "./data:/var/lib/xwash/data"
    environment:
      MYSQL_ROOT_PASSWORD: c%>PQ799@!
#    command:
#      - bash -c "bash /var/lib/xwash/data/init.sh"
    ports:
      - "3306:3306"

  redis:
    restart: always
    image: redis
    ports:
      - "13579:6379"
