name: Deploy

on:
  push:
    # 分支
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java 8 compile
    steps:
      - uses: actions/checkout@v2
      - name: Add mysql password into jdbc.properties
        - run |
          echo ${{ MYSQL_PASSWORD }} >> src/main/resources/mapper/jdbc.properties
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'zulu'
          java-version: '8.0.322+6'
      - name: Cache maven repo
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Package war
        run: mvn package
      - name: Send war
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./target/xWash.war"
          target: ${{ secrets.REMOTE }}
